general {
    lock_cmd = omarchy-lock-screen                         # lock screen and 1password
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on             # to avoid having to press a key twice to turn on the display.
    inhibit_sleep = 3                                      # wait until screen is locked
}

listener {
    timeout = 150                                             # 2.5min
    # Respect screensaver toggle and fork idle-disabled toggle
    on-timeout = bash -lc '[[ -f ~/.local/state/omarchy/toggles/idle-disabled ]] || pidof hyprlock || omarchy-launch-screensaver'
}

listener {
    timeout = 300                      # 5min
    # Respect fork idle-disabled toggle
    on-timeout = bash -lc '[[ -f ~/.local/state/omarchy/toggles/idle-disabled ]] || loginctl lock-session'
}

listener {
    timeout = 330                                            # 5.5min
    # Respect fork idle-disabled toggle
    on-timeout = bash -lc '[[ -f ~/.local/state/omarchy/toggles/idle-disabled ]] || hyprctl dispatch dpms off'
    on-resume = bash -lc '[[ -f ~/.local/state/omarchy/toggles/idle-disabled ]] || (hyprctl dispatch dpms on && brightnessctl -r)'
}
